name: Validate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Go mod download
        run: go mod download

      - name: Run linters
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest
          args: --timeout=10m

      - name: Build
        run: |
          set -euo pipefail

          mkdir -p ./dist
          go build -o ./dist -v .

  generate:
    name: Generate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: tools/go.mod
          cache: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Generate
        working-directory: ./tools
        run: |
          set -euo pipefail

          go mod download
          go generate ./...

      - name: Check diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    outputs:
      tf_versions: ${{ steps.setup.outputs.tf_versions }}
      k8s_versions: ${{ steps.setup.outputs.k8s_versions }}
    steps:
      - name: Setup
        id: setup
        run: |
          set -euo pipefail

          tf_versions="$(curl -s https://endoflife.date/api/terraform.json | jq -rc '[sort_by(.releaseDate) | reverse | .[0:4] | .[].latest]')"
          k8s_versions="$(curl -s https://endoflife.date/api/kubernetes.json | jq -rc '[sort_by(.releaseDate) | reverse | .[0:4] | .[].latest]')"

          {
            echo "tf_versions=${tf_versions}"
            echo "k8s_versions=${k8s_versions}"
          } >> "${GITHUB_OUTPUT}"

  test:
    name: Test
    needs:
      - build
      - generate
      - matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        tf_version: ${{ fromJson(needs.matrix.outputs.tf_versions) }}
        k8s_version: ${{ fromJson(needs.matrix.outputs.k8s_versions) }}
    env:
      KUBE_CONFIG_PATH: ${{ github.workspace }}/.kube/config
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Crane
        uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4

      - name: Setup
        id: setup
        run: |
          set -euo pipefail

          k8s_version="${{ matrix.k8s_version }}"
          k8s_major="$(echo "${k8s_version}" | cut -d. -f1)"
          k8s_minor="$(echo "${k8s_version}" | cut -d. -f2)"

          regex="^v${k8s_major}\.${k8s_minor}\.[0-9]+$"
          kind_node_tag="v$(crane ls --omit-digest-tags docker.io/kindest/node | grep -E "${regex}" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | jq -sRr '[split("\n") | .[] | select(. != "")] | sort_by(. | split(".") | map(tonumber)) | .[-1]')"

          echo "kind_node_tag=${kind_node_tag}" >> "${GITHUB_OUTPUT}"

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.tf_version }}
          terraform_wrapper: false

      - name: Create Kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          kubeconfig: ${{ env.KUBE_CONFIG_PATH }}
          node_image: kindest/node:${{ steps.setup.outputs.kind_node_tag }}
          wait: 2m

      - name: Go mod download
        run: go mod download

      - name: Test
        env:
          TF_ACC: "1"
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.tf_version }}
        run: go test -v -timeout 120m -cover ./...

  check:
    name: Check
    needs:
      - build
      - generate
      - test
    if: always()
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check
        run: |
          set -euo pipefail
          results=( ${{ join(needs.*.result, ' ') }} )
          for result in "${results[@]}"; do
            if [[ "${result}" == "failure" ]] || [[ "${result}" == "cancelled" ]]; then
              echo "::error::Workflow failed!"
              exit 1
            fi
          done
